include:
  # ----------------------------- resets -----------------------------
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: _reset/reset-seeduino-xiao

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: _reset/reset-nice-nano

  # ----------------------------- nuke_pad --------------------------
  - board: nice_nano_v2
    shield: nuke_pad
    artifact-name: nuke-pad/nuke-pad

  # ----------------------------- enki42 ---------------------------
  - board: seeeduino_xiao_ble
    shield: enki_left led_indicator
    snippet: common-config
    artifact-name: enki/enki-left

  - board: seeeduino_xiao_ble
    shield: enki_right led_indicator
    snippet: common-config
    artifact-name: enki/enki-right

  # ----------------------------- totem38 ----------------------------
  - board: seeeduino_xiao_ble
    shield: totem_left led_indicator
    snippet: common-config
    artifact-name: totem/totem-left

  - board: seeeduino_xiao_ble
    shield: totem_right led_indicator
    snippet: common-config
    artifact-name: totem/totem-right

  # ----------------------------- chonky34 ----------------------------
  - board: nice_nano_v2
    shield: chonky_bois_left led_indicator
    snippet: common-config
    artifact-name: chonky/chonky-left

  - board: nice_nano_v2
    shield: chonky_bois_right led_indicator
    snippet: common-config
    artifact-name: chonky/chonky-right

    # ----------------------------- sofle58 ----------------------------
  - board: nice_nano_v2
    shield: sofle_left
    artifact-name: sofle/sofle-left

  - board: nice_nano_v2
    shield: sofle_right
    artifact-name: sofle/sofle-right

  # ----------------------------- enki42 dongle -----------------------
  - board: seeeduino_xiao_ble
    shield: enki_left
    snippet: common-config
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: enki-dongle/enki-dongle-left

  - board: seeeduino_xiao_ble
    shield: enki_right
    snippet: common-config
    artifact-name: enki-dongle/enki-dongle-right

  - board: seeeduino_xiao_ble
    shield: enki_dongle dongle_screen
    artifact-name: enki-dongle/enki-dongle-central

  # ----------------------------- totem38 dongle ----------------------
  - board: seeeduino_xiao_ble
    shield: totem_left
    snippet: common-config
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: totem-dongle/totem-dongle-left

  - board: seeeduino_xiao_ble
    shield: totem_right
    snippet: common-config
    artifact-name: totem-dongle/totem-dongle-right

  - board: seeeduino_xiao_ble
    shield: totem_dongle dongle_screen
    artifact-name: totem-dongle/totem-dongle-central

  # ----------------------------- chonky34 dongle ---------------------
  - board: nice_nano_v2
    shield: chonky_bois_left
    snippet: common-config
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: chonky-dongle/chonky-dongle-left

  - board: nice_nano_v2
    shield: chonky_bois_right
    snippet: common-config
    artifact-name: chonky-dongle/chonky-dongle-right

  - board: seeeduino_xiao_ble
    shield: chonky_bois_dongle dongle_screen
    artifact-name: chonky-dongle/chonky-dongle-central
