manifest:
  defaults:
    revision: main
    remote: urob

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: janpfischer
      url-base: https://github.com/janpfischer

    - name: urob
      url-base: https://github.com/urob

    - name: englmaxi
      url-base: https://github.com/englmaxi

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml

    - name: zmk-helpers
    - name: zmk-unicode
    - name: zmk-tri-state

    - name: zmk-dongle-screen
      remote: janpfischer

    - name: zmk-rgbled-widget
      url: https://github.com/caksoylar/zmk-rgbled-widget
      revision: v0.3

    - name: zmk-dongle-display
      remote: englmaxi
      revision: v0.3 

  self:
    path: config
