CONFIG_ZMK_BLE=y


# sleep
CONFIG_ZMK_IDLE_TIMEOUT=300000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=2147483647

# bt
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
# CONFIG_BT_MAX_CONN=2
# CONFIG_BT_MAX_PAIRED=2
# CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# # battery 
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# studio
CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_STUDIO_LOCKING=n

# mouse 
# CONFIG_ZMK_POINTING=y
# CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# # rgb widget
# CONFIG_RGBLED_WIDGET=y
# CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y



##### sofle

# Uncomment the following line to enable the Sofle OLED Display
CONFIG_ZMK_DISPLAY=y

# Uncomment these two lines to add support for encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# RGB Underglow - keys 
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n

CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=240
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=10

# Backlight - bottom    
# CONFIG_ZMK_BACKLIGHT=y
# CONFIG_ZMK_BACKLIGHT_ON_START=n  
# CONFIG_ZMK_BACKLIGHT_AUTO_OFF_IDLE=y

# Uncomment the line below to disable external power toggling by the underglow.
# By default toggling the underglow on and off also toggles external power
# on and off. This also causes the display to turn off.
# CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# Turn off RGB underglow when USB is disconnected	
# CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y

# Automatically turn off underglow when keyboard is not touched for 30s
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
