# Use the keymap-drawer ZMK user config workflow
# https://github.com/caksoylar/keymap-drawer#setting-up-an-automated-drawing-workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch: 
  push: 
    paths:
      - ".github/workflows/draw-keymaps.yml"
      - "keymap-drawer/keymap_drawer.config.yaml"
      - "boards/shields/*/*.json"
      - "config/**"
      
jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      commit_message: "[Draw] ${{ github.event.head_commit.message }}"
      amend_commit: true
      # fail_on_error: true
      keymap_patterns: "config/*.keymap"
      config_path: "keymap-drawer/keymap_drawer.config.yaml"
      json_path: "boards/shields/${keyboard}"
      output_folder: "keymap-drawer/svg"
      destination: "both"
      # draw_args: "totem:'--ghost-keys 0 9 26 29'"
      